name: Notification CI Manager

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Actions for Discord
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: 'New commit to **${{ github.event.repository.name }}** from
            **${{ github.event.head_commit.author.name }}**:

            ${{ github.event.head_commit.url }}

            *Commit Message*: \"${{ github.event.head_commit.message }}\"'

